### PR TITLE
Use Redux in React components.

### PR DESCRIPTION
**Pull request by TesheMaximillan**
# In this milestone I followed the following requirements 📌🧰

> In this milestone I used the Redux store to display books. also, used functionalities like `useDispatch` and `useSelector` from react-redux library

* States are immutable.
* Initial state is changed by default value.
* Redux provider is imported to the main component (`index.js`)
* App is connected to Redux store
* List of books are displayed in redux store
* Books are added by using the `useDispatch` method
* Books are removed by using the `useDispatch` method
* Check status functionality added when the button is clicked

### CODE REVIEW

**Review by mikethreels — CHANGES_REQUESTED** [review]
Hi Teshome, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] when adding a list of books the application works fine however when trying to delete 1 book it deletes all the books that were added, this is due to the fact that the application gives all the new books the same ID as you can see in the below screenshot.
Screenshot 2022-05-03 222734


Cheers and Happy coding!👏👏�


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TesheMaximillan** [comment]
I used `uuid` library for the id, also, it was working fine on my side
screenshotcode

**Comment by TesheMaximillan** [comment]
Sorry, now I understood what you mean, I will make the change accordingly. Thank you for your feedback.

**Review by FrederickMih — APPROVED** [review]
Hi @TesheMaximillan , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
